---

- name: "Remove {{ goss_test_directory }}"
  file:
    path: "{{ goss_test_directory }}"
    state: absent

- name: Remove goss
  file:
    path: "{{ goss_path }}/goss"
    state: absent

- name: Remove dgoss
  file:
    path: "{{ goss_path }}/dgoss"
    state: absent
