---
- name: Install ca-certificates
  apt:
    name: ca-certificates
  when: ansible_os_family == 'Debian'

- name: "get goss binary"
  become: no
  delegate_to: localhost
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-amd64"
    validate_certs: no #  for the proxy chain
    dest: "/tmp/goss"
    mode: 0755

- name: "copy goss to remote"
  copy:
    src: "/tmp/goss"
    dest: "{{ goss_path }}/goss"
    mode: 0755

- name: "copy dgoss to remote"
  copy:
    src: "dgoss"
    dest: "{{ goss_path }}/dgoss"
    mode: 0755
  no_log: yes

- name: "copy goss.yaml to remote"
  template:
    src: goss.yaml
    dest: /root/goss.yaml

- name: "copy test_goss.yml to remote"
  template:
    src: goss.yaml
    dest: /root/test_goss.yml
