---
- name: Install ca-certificates
  apt:
    name: ca-certificates
  when: ansible_os_family == 'Debian'
  tags:
    - base_goss

- name: "get goss binary"
  become: no
  delegate_to: localhost
  retries: 5
  delay: 5
  get_url:
    url: "https://github.com/aelsabbahy/goss/releases/download/{{ goss_version }}/goss-linux-amd64"
    validate_certs: no  # for the proxy chain
    dest: "/tmp/goss"
    mode: 0755
  tags:
    - base_goss

- name: "copy goss to remote"
  copy:
    src: "/tmp/goss"
    dest: "{{ goss_path }}/goss"
    mode: 0755
  tags:
    - base_goss

- name: "copy dgoss to remote"
  copy:
    src: "dgoss"
    dest: "{{ goss_path }}/dgoss"
    mode: 0755
  no_log: yes
  tags:
    - base_goss

- name: "verify if /root/goss.yaml exists"
  stat:
    path: /root/goss.yaml
  register: yamlfile
  tags:
    - base_goss

- name: "copy goss.yaml to remote"
  template:
    src: goss.yaml
    dest: /root/goss.yaml
  when: not yamlfile.stat.exists
  tags:
    - base_goss

- name: "copy test_goss.yml to remote"
  template:
    src: goss.yaml
    dest: /root/test_goss.yml
  tags:
    - base_goss

- name: Register test files
  shell: "ls {{ goss_test_directory }}/test_*.yml"
  register: test_files
  changed_when: false
  tags:
    - base_goss
    - validate

- name: Execute Goss tests
  command: "{{ goss_dst }} -g {{ item }} validate --format {{ goss_format }}"
  register: test_results
  with_items: "{{ test_files.stdout_lines }}"
  changed_when: false
  tags:
    - base_goss
    - validate

- name: Display details about the Goss results
  debug:
    msg: "{{ item.stdout_lines }}"
  with_items: "{{ test_results.results }}"
  tags:
    - base_goss
    - validate

- name: Fail when tests fail
  fail:
    msg: "Goss failed to validate"
  when: item.rc != 0
  with_items: "{{ test_results.results }}"
  tags:
    - base_goss
    - validate
