---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-goss-centos7
    image: centos:7
    privileged: true
  - name: base-goss-bionic
    image: ubuntu:bionic
    privileged: true
  - name: base-goss-debian9
    image: debian:stretch
    privileged: true
  - name: base-goss-debian10
    image: debian:buster
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
