---
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: base-goss-centos
    image: centos:7
    privileged: True
  - name: base-goss-ubuntu
    image: ubuntu
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
scenario:
  name: default
